export const GET_CALENDARS = 'GET_CALENDARS'
export const SET_CALENDARS = 'SET_CALENDARS'

export const ADD_EVENT_TO_SHAREPOINT = 'ADD_EVENT_TO_SHAREPOINT'
export const GET_EVENTS = 'GET_EVENTS'
export const SET_EVENTS = 'SET_EVENTS'

export const GET_FORM_DIGEST_VALUE = 'GET_FORM_DIGEST_VALUE'
export const SET_FORM_DIGEST_VALUE = 'SET_FORM_DIGEST_VALUE'
